services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  vertica:
    image: jbfavre/vertica
    environment:
      - DATABASE_NAME=test
      - DB_USER=dbadmin
      - PASSWORD=password
    ports:
      - "5433:5433"
    volumes:
      - vertica_data:/data

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./bench.ipynb:/home/jovyan/work/bench.ipynb
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - clickhouse
      - vertica

volumes:
  clickhouse_data:
  vertica_data:
  notebooks:
